# Generated by Django 6.0.4 on 2026-04-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('version', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('publish_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
