# Generated by Django 6.0.4 on 2026-04-19 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
        ('catagory', '0005_catagory_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='catagory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catagory.catagory'),
            preserve_default=False,
        ),
    ]
