# Generated by Django 6.0.4 on 2026-04-19 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catagory', '0002_alter_catagory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
