# Generated by Django 6.0.4 on 2026-04-19 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catagory', '0003_alter_catagory_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
