# Generated by Django 6.0.4 on 2026-04-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catagory', '0004_alter_catagory_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='catagory',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
